FromDoppler/doppler-html-editor-api

README.md

Update readme information

---

README.md

fix: readme content

---

Doppler.HtmlEditorApi/Controllers/CampaignsController.cs
Doppler.HtmlEditorApi/Controllers/TemplatesController.cs
Doppler.HtmlEditorApi/Model/Campaign.cs

Add endpoints with dummies responses

Add endpoints to Editors API

---

Doppler.HtmlEditorApi.Test/GetCampaignTest.cs
Doppler.HtmlEditorApi/Controllers/CampaignsController.cs
Doppler.HtmlEditorApi/Infrastructure/CampaignContentRequest.cs
Doppler.HtmlEditorApi/Infrastructure/ContentRow.cs
Doppler.HtmlEditorApi/Infrastructure/DummyRepository.cs
Doppler.HtmlEditorApi/Infrastructure/IRepository.cs
Doppler.HtmlEditorApi/Infrastructure/Repository.cs
Doppler.HtmlEditorApi/Model/Campaign.cs
demo.http

This implementation change the getCampaign return used in [DE-400](https://makingsense.atlassian.net/browse/DE-400)

[DE-395] Save unlayer model in doppler

---

Doppler.HtmlEditorApi/Model/Campaign.cs

Update campaign model mapping adding all available tools from Unlayer.

Update campaign model

---

Doppler.HtmlEditorApi/Controllers/CampaignsController.cs

Thanks @ms-darianbenito! https://github.com/FromDoppler/doppler-html-editor-api/pull/23#discussion_r794763672

fix: dispose JsonDocument

---

Doppler.HtmlEditorApi.Test/GetCampaignTest.cs
Doppler.HtmlEditorApi.Test/SaveCampaignTest.cs
Doppler.HtmlEditorApi/Controllers/CampaignsController.cs
Doppler.HtmlEditorApi/Infrastructure/ContentRow.cs
Doppler.HtmlEditorApi/Infrastructure/Repository.cs
Doppler.HtmlEditorApi/Model/ContentType.cs

Hi team!
It should allow us to edit HTML campaign content, could you review it?

DE-450 - Support html content

---

Doppler.HtmlEditorApi.Test/GetCampaignTest.cs
Doppler.HtmlEditorApi.Test/SaveCampaignTest.cs
Doppler.HtmlEditorApi/Infrastructure/ContentRow.cs
Doppler.HtmlEditorApi/Model/Campaign.cs
Doppler.HtmlEditorApi/Model/ContentType.cs
README.md

Hi team!
The DB model was different than I thought, I have done a little exploration and documented the result in our README file.
Then, I changed the system behavior based on that. I think that the tests represent the fix very well, you can read them to understand my changes.

DE-450 - Fix HTML content related behavior

---

Doppler.HtmlEditorApi.Test/GetCampaignTest.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/FirstOrDefaultContentWithCampaignStatusDbQuery.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/Repository.cs

Typed query improvements

---

Doppler.HtmlEditorApi.Test/GetCampaignTest.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/Repository.cs

Hi team!
This PR is to take advantage of the new typed queries in the tests.
The next step is to refactor the pending queries in the same way and increment the test coverage.

Improve tests

---

Doppler.HtmlEditorApi.Test/GetCampaignTest.cs
Doppler.HtmlEditorApi.Test/SaveCampaignTest.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/DapperWrapperDbContext.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/IDbContext.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/ByCampaignIdAndAccountNameParameters.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/ContentRow.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/FirstOrDefaultCampaignStatusDbQuery.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/FirstOrDefaultContentWithCampaignStatusDbQuery.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/InsertCampaignContentDbQuery.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/UpdateCampaignContentDbQuery.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/Repository.cs

Types, types, types, and more types!
Tests, tests, tests, and more tests!

Update typed queries

---

Doppler.HtmlEditorApi/Controllers/CampaignsController.cs
Doppler.HtmlEditorApi/FieldAliasesDef.cs
Doppler.HtmlEditorApi/FieldsOptions.cs
Doppler.HtmlEditorApi/Startup.cs
Doppler.HtmlEditorApi/appsettings.json

It removes the hardcoding aliases from the controller and moves them to the configuration.
Could you review?

DE-499 - Read field name aliases from configuration

---

Doppler.HtmlEditorApi.Test/HtmlContentProcessingIntegrationTests.cs
Doppler.HtmlEditorApi.Test/SaveCampaignTest.cs
Doppler.HtmlEditorApi.Test/Utils/IDbContextMockExtensions.cs
Doppler.HtmlEditorApi/Controllers/CampaignsController.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/DapperFieldsRepository.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/DapperWrapperDbContext.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/IDbContext.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/DbQuery.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/QueryActiveBasicFieldsDbQuery.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/ServiceCollectionExtensions.cs
Doppler.HtmlEditorApi/Storage/IFieldsRepository.cs

Hi team!
This PR adds the fields' repository to read the basic fields from DB, I am going to create a new PR for the custom fields.

DE-498 Read basic fields from DB

---

Doppler.HtmlEditorApi.Test/HtmlContentProcessingIntegrationTests.cs
Doppler.HtmlEditorApi.Test/Utils/IDbContextMockExtensions.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/DapperFieldsRepository.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/DapperWrapperDbContext.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/IDbContext.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/ByAccountNameParameters.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/DbField.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/QueryActiveBasicFieldsDbQuery.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/QueryCustomFieldsDbQueryByAccountNameDbQuery.cs

Hi team!
With these changes, we are reading the custom fields from the database and replacing the tags by the IDs on saving the HTML.

DE-504 - Read custom fields from DB

---

Doppler.HtmlEditorApi.Test/DopplerHtmlDocumentTest.cs
Doppler.HtmlEditorApi.Test/SaveCampaignTest.cs
Doppler.HtmlEditorApi/Controllers/CampaignsController.cs
Doppler.HtmlEditorApi/DopplerHtmlDocument.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/DapperFieldsRepository.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/SaveNewFieldIds.cs
Doppler.HtmlEditorApi/Storage/IFieldsRepository.cs

Hi team!
I know that it is arguable (we can argue on that).
But I think these changes would help us to avoid misunderstandings in the future.

DE-475 - Minor refactoring

---

Doppler.HtmlEditorApi.Test/SaveCampaignTest.cs
Doppler.HtmlEditorApi.Test/Storage/Queries/SaveNewCampaignLinksTest.cs
Doppler.HtmlEditorApi/Controllers/CampaignsController.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/DapperCampaignContentRepository.cs
Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/SaveNewCampaignLinks.cs
Doppler.HtmlEditorApi/Storage/ICampaignContentRepository.cs

Hi team!
It extracts the links from the content and stores the new ones in the `Links` table.

DE-521 - Save new links

---

Doppler.HtmlEditorApi.Test/Utils/AssertHelper.cs
Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/PutCampaignTest.cs

It will help us to have a better output when the comparison fails.

test: fix helper to lax string comparison

---

Doppler.HtmlEditorApi.Test/Utils/IDbContextMockExtensions.cs
Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/GetCampaignTest.cs
Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/PutCampaignTest.cs
Doppler.HtmlEditorApi/ApiModels/Campaign.cs
Doppler.HtmlEditorApi/ApiModels/Content.cs
Doppler.HtmlEditorApi/ApiModels/Template.cs
Doppler.HtmlEditorApi/Controllers/CampaignsController.cs
Doppler.HtmlEditorApi/Domain/ContentData.cs
Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerCampaignContentRepository.cs
Doppler.HtmlEditorApi/Repositories.DopplerDb/Queries/FirstOrDefaultContentWithCampaignStatusDbQuery.cs
Doppler.HtmlEditorApi/Repositories.DopplerDb/Queries/UpdateCampaignPreviewImageDbQuery.cs

Hi team! it adds the necessary code to get and update the `PreviewImage` field with our API.
⚠️ It cannot be released before https://github.com/MakingSense/Doppler/pull/9286

DE-560 - Store image preview

---

Doppler.HtmlEditorApi/Controllers/CampaignsController.cs
Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerCampaignContentRepository.cs
Doppler.HtmlEditorApi/Repositories.DopplerDb/Queries/UpdateCampaignStatusDbQuery.cs
Doppler.HtmlEditorApi/Repositories/ICampaignContentRepository.cs

[DE-613] Separate update campaign status and preview image methods

---

Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/PutCampaignTest.cs
Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerCampaignContentRepository.cs

When campaign type is Classic, the value of TestType should be null.

[DE-613] Update DopplerCampaignTypeClassic value to null

---

Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/GetCampaignTest.cs
Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/PutCampaignTest.cs
Doppler.HtmlEditorApi/Controllers/CampaignsController.cs
Doppler.HtmlEditorApi/Domain/ContentData.cs
Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerCampaignContentRepository.cs
Doppler.HtmlEditorApi/Repositories/ICampaignContentRepository.cs

Hi team, 
we need to refactor contentRow in order to extract campaignId because we'll need this parameters to iterate the update and creation of Test AB Campaigns.

[DE-613] Extract CampaignId from contentRow and related methods

---

Doppler.HtmlEditorApi/Controllers/CampaignsController.cs
Doppler.HtmlEditorApi/Domain/TemplateData.cs
Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerTemplateRepository.cs

There was a wrong condition, so, when the template has an IdUser, the generated content is wrong.
I have also applied some code refactoring to protect the programmer from these kinds of errors.

DE-682 - fix user template

---

Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/GetCampaignTest.cs
Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/from-template/_/CreateCampaignContentFromTemplateTest.cs
Doppler.HtmlEditorApi/ApiModels/Campaign.cs
Doppler.HtmlEditorApi/ApiModels/Content.cs
Doppler.HtmlEditorApi/Controllers/CampaignsController.cs
Doppler.HtmlEditorApi/Domain/ContentData.cs
Doppler.HtmlEditorApi/Domain/TemplateData.cs
Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerCampaignContentRepository.cs
Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerTemplateRepository.cs
Doppler.HtmlEditorApi/Repositories.DopplerDb/Queries/FirstOrDefaultContentWithCampaignStatusDbQuery.cs
Doppler.HtmlEditorApi/Repositories.DopplerDb/Queries/GetTemplateByIdWithStatusDbQuery.cs

[DE-688] add name field to GetCampaign response

---

Doppler.HtmlEditorApi.Test/Utils/IDbContextMockExtensions.cs
Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/from-template/_/CreateCampaignContentFromTemplateTest.cs

I will use some of these refactorings for the new tests for _GET Template_.

Clean up CreateCampaignContentFromTemplateTest

---

.vscode/launch.json
Dockerfile
Doppler.HtmlEditorApi.Test/Doppler.HtmlEditorApi.Test.csproj
Doppler.HtmlEditorApi/Dockerfile
Doppler.HtmlEditorApi/Doppler.HtmlEditorApi.csproj
Doppler.HtmlEditorApi/Startup.cs

Update to .NET 7

---

Doppler.HtmlEditorApi.Test/http/accounts/_/templates/_/GetTemplateTest.cs
Doppler.HtmlEditorApi/ApiModels/Template.cs
Doppler.HtmlEditorApi/Controllers/TemplatesController.cs

Hi team!
This is to get the template content using our API!

Allow to get templates by id

---

Doppler.HtmlEditorApi.Test/Repositories.DopplerDb/DopplerTemplateRepositoryTest.cs
Doppler.HtmlEditorApi.Test/Utils/IDbContextMockExtensions.cs
Doppler.HtmlEditorApi.Test/http/accounts/_/templates/_/PutTemplateTest.cs
Doppler.HtmlEditorApi/ApiModels/Template.cs
Doppler.HtmlEditorApi/Controllers/TemplatesController.cs
Doppler.HtmlEditorApi/Domain/DopplerHtmlDocument.cs
Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerTemplateRepository.cs
Doppler.HtmlEditorApi/Repositories.DopplerDb/Queries/UpdateTemplateDbQuery.cs
Doppler.HtmlEditorApi/Repositories/ITemplateRepository.cs

I did not test it yet, but you can start to review it...

DE-872 - PUT template

---

Doppler.HtmlEditorApi.Test/Repositories.DopplerDb/DopplerTemplateRepositoryTest.cs
Doppler.HtmlEditorApi.Test/Utils/IDbContextMockExtensions.cs
Doppler.HtmlEditorApi/Repositories.DopplerDb/Queries/CreatePrivateTemplateDbQuery.cs
Doppler.HtmlEditorApi/Repositories.DopplerDb/Queries/UpdateTemplateDbQuery.cs

I was missing to save some data:

Missing template data

---

Doppler.HtmlEditorApi.Test/http/accounts/_/templates/PostTemplatesTest.cs
Doppler.HtmlEditorApi/Controllers/TemplatesController.cs

Now we can create a private template using the endpoint **POST**:**_/accounts/{accountName}/templates_**
Jira: [DE-869](https://makingsense.atlassian.net/browse/DE-869)
[DE-869]: https://makingsense.atlassian.net/browse/DE-869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DE-869] Create private template

---

Dockerfile
Doppler.HtmlEditorApi.Test/Domain/DopplerHtmlDocumentTest.cs
Doppler.HtmlEditorApi.Test/Repositories.DopplerDb/Queries/SaveNewCampaignLinksTest.cs
Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/PutCampaignTest.cs
Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/from-template/_/CreateCampaignContentFromTemplateTest.cs
Doppler.HtmlEditorApi/Domain/DopplerHtmlDocument.cs
Doppler.HtmlEditorApi/DopplerSecurity/DopplerSecurityServiceCollectionExtensions.cs
Doppler.HtmlEditorApi/DopplerSecurity/IsOwnResourceAuthorizationHandler.cs
Doppler.HtmlEditorApi/Logging/SerilogSetup.cs
Doppler.HtmlEditorApi/Program.cs
cspell-project-words.txt
cspell.json
package.json
yarn.lock

I am not sure about this change, could you review it and let me know your opinion?

Add cspell

---

Dockerfile
Doppler.HtmlEditorApi.Test/Domain/DopplerHtmlDocumentTest.cs
Doppler.HtmlEditorApi/Domain/DopplerHtmlDocument.cs

fix: fix URL parsing when it has `?` but no `/`

---

Doppler.HtmlEditorApi.Test/Domain/DopplerHtmlDocumentTest.cs
Doppler.HtmlEditorApi/Domain/DopplerHtmlDocument.cs

Remove encode & to save links on DB as Doppler format required

Dop 1520 save content links

---

Doppler.HtmlEditorApi.Test/Domain/DopplerHtmlDocumentTest.cs
Doppler.HtmlEditorApi/Controllers/CampaignsController.cs
Doppler.HtmlEditorApi/Domain/DopplerHtmlDocument.cs

Update SanitizeDynamicContentNodes method for multiples dynamic contents

DOP-1401 - Recommended product

---

Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/promo-code/CreatePromoCodeTest.cs
Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/promo-code/_/PutPromoCodeTest.cs
Doppler.HtmlEditorApi/ApiModels/PromoCode.cs
Doppler.HtmlEditorApi/Controllers/CampaignsController.cs
Doppler.HtmlEditorApi/Domain/PromoCodeModel.cs
Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerDbServiceCollectionExtensions.cs
Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerPromoCodeRepository.cs
Doppler.HtmlEditorApi/Repositories.DopplerDb/Queries/InsertPromoCodeDbQuery.cs
Doppler.HtmlEditorApi/Repositories.DopplerDb/Queries/UpdatePromoCodeDbQuery.cs
Doppler.HtmlEditorApi/Repositories/IPromoCodeRepository.cs

Add new methods and test to insert and update promocodes from unlayer editor

Add promo code methods

---

Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerPromoCodeRepository.cs
Doppler.HtmlEditorApi/Repositories.DopplerDb/Queries/UpdatePromoCodeDbQuery.cs

chore: remove campaignId from update promocode
