Doppler.HtmlEditorApi/Infrastructure/CampaignContentRequest.cs, Doppler.HtmlEditorApi/Infrastructure/Repository.cs
Recibimos el modelo de Unlayer sin modificaciones en la data y sin tener en cuanta la estructura de `ContentModel` que tenemos definida en la API, el objetivo es no perder ningún dato generado por Unlayer.
<s>Se decide recibir un objeto **JSON** por encima de un dato tipo **String** para quitar al cliente _(quien hace la petición)_ la responsabilidad de hacer escape de los datos, de esta manera en la petición viaja un objeto JSON y la API decide como hacer escape de la data entrante.</s>
El cliente _(quien hace la petición)_ puede enviar un **JSON** o un objeto JSON como **string**
- Meta JSON: `{"prop": "value"}`
- Meta string: `"{\"prop\":\"value\"}"`
=> [DE-435] Recibir el modelo del contenido Unlayer sin modificaciones

Jenkinsfile
Hi team! 
It is to easily release working progress branches to INT.
When the branch is INT, it will avoid:
* Verify git commit conventions
* Verify Format
* Verify .sh files
* Test
What do you think?
=> build: reduce verifications for publishing to INT environment

Doppler.HtmlEditorApi/Infrastructure/Repository.cs
Hi team! 
I think that this implementation is safer and more predictable.
---
* Campaña: _propia_
* Contenido: _existe_
* Tipo de contenido: _unlayer (5)_
➡ Se actualiza la fila (como antes)
* Campaña: _propia_
* Contenido: _no existe_
* Tipo de contenido: _N/A_
➡ Se inserta la fila (como antes)
* Campaña: _de otro usuario_
* Contenido: _existe_
* Tipo de contenido: _unlayer (5)_
➡ Error porque "la campaña no existe o pertenece a otro usuario" (~ similar al comportamiento anterior)
* Campaña: _de otro usuario_
* Contenido: _existe_
* Tipo de contenido: _otro_
➡ Error porque "la campaña no existe o pertenece a otro usuario" (~ similar al comportamiento anterior)
* Campaña: _propia_
* Contenido: _existe_
* Tipo de contenido: _otro_
➡ Se actualizará el contenido y tipo (cambio de …
=> DE-445 - Only update own campaigns

Doppler.HtmlEditorApi/Controllers/CampaignsController.cs, Doppler.HtmlEditorApi/Infrastructure/ContentRow.cs, Doppler.HtmlEditorApi/Infrastructure/Repository.cs
This PR validates if
- Campaign exists
- Campaign belongs to account
- Campaign has content.
If doesn't exists or belongs to a different user, repository returns null.
If hasn't any content, repository returns an empty contentRow.
If none of these scenarios occurs, repository returns query result.
=> Check if campaign exists, belongs to account and has content

Doppler.HtmlEditorApi.Test/GetCampaignTest.cs, Doppler.HtmlEditorApi.Test/SaveCampaignTest.cs, Doppler.HtmlEditorApi/Controllers/CampaignsController.cs, Doppler.HtmlEditorApi/Infrastructure/ContentRow.cs, Doppler.HtmlEditorApi/Infrastructure/DummyRepository.cs, Doppler.HtmlEditorApi/Model/Campaign.cs, Doppler.HtmlEditorApi/Model/Content.cs, Doppler.HtmlEditorApi/Model/ContentType.cs, Doppler.HtmlEditorApi/Model/Template.cs, Doppler.HtmlEditorApi/Startup.cs, Doppler.HtmlEditorApi/Utils.cs
Hi team!
In this PR I am preparing the codebase to deal with a new content type.
These changes are introducing a minor breaking change that [we are already ready to deal with in the WebApp](https://github.com/FromDoppler/doppler-editors-webapp/pull/101): After merging this, the field `type` will be included and **also required** in the API payloads.
=> DE-450 - Preparation for the new content type

Doppler.HtmlEditorApi.Test/Doppler.HtmlEditorApi.Test.csproj, Doppler.HtmlEditorApi.Test/GetCampaignTest.cs, Doppler.HtmlEditorApi.Test/Utils/AssertHelper.cs, Doppler.HtmlEditorApi/Startup.cs, Doppler.HtmlEditorApi/Storage.DapperProvider/DapperWrapperDbContext.cs, Doppler.HtmlEditorApi/Storage.DapperProvider/IDbContext.cs, Doppler.HtmlEditorApi/Storage.DapperProvider/Repository.cs, Doppler.HtmlEditorApi/Storage.DapperProvider/ServiceCollectionExtensions.cs
Hi team!
In other projects, we are using [Moq.Dapper](https://github.com/UnoSD/Moq.Dapper), but I found it too limited and uncomfortable for the usage.
There is a nice discussion about the topic of testing Dapper: https://github.com/DapperLib/Dapper/issues/1074
I liked the approach of [DataAbstractions.Dapper](https://github.com/codeapologist/DataAbstractions.Dapper), but I think that by the moment, in place of wrapping the IDbConnection, it could be a good idea to add a new abstraction for the _DB context_ with scoped lifetime.
Also, probably we will use only a couple of Dapper methods and I do not like to have all Dapper methods available.
I only migrate one test to the new approach. As you see, mocking dynamic methods is not so nice. So, the next steps are:
* Add types for the queries' …
=> Wrap Dapper

Dockerfile
Something happened with the SDK 6.0.200 that breaks `dotnet format`.
At the moment, I am downgrading to the previous version. We could research it later.
=> fix: test CI

Doppler.HtmlEditorApi.Test/GetCampaignTest.cs, Doppler.HtmlEditorApi/Storage.DapperProvider/DapperWrapperDbContext.cs, Doppler.HtmlEditorApi/Storage.DapperProvider/IDbContext.cs, Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/DbQuery.cs, Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/FirstOrDefaultContentWithCampaignStatusDbQuery.cs, Doppler.HtmlEditorApi/Storage.DapperProvider/Repository.cs
Hi team!
This PR updates one of our queries to be type-safe.
Encapsulating the extension method, the query, the parameters type, and the result type in a static class could look weird. But in my opinion, it is a way to keep together the things that are changed together.
What do you think?
---
It is pending to apply this same approach to the other queries and update the tests to take advantage of this.
=> Typed query data

Doppler.HtmlEditorApi.Test/SaveCampaignTest.cs, Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/UpdateCampaignStatusDbQuery.cs, Doppler.HtmlEditorApi/Storage.DapperProvider/Repository.cs
Hi team!
We have two entities: the campaign and the content.
Previously, we tough that Doppler would understand that the campaign has content if it exists. So, as we have an idempotent API, we simply inserted or updated the content: https://github.com/FromDoppler/doppler-html-editor-api/blob/a2c2805a73dc912cbb064d5eb5aefd17372abfc3/Doppler.HtmlEditorApi/Storage.DapperProvider/Repository.cs#L80-L82
But Doppler did not understand that: 
Besides to create the content, we need to increment the `CurrentStep` from `1` to `2` and set [`HtmlSourceType`](https://github.com/MakingSense/Doppler/blob/48cf637bb1f8b4d81837fff904d8736fe889ff1c/Doppler.Transversal/Classes/CampaignHTMLContentTypeEnum.cs#L12-L17).
After these changes, I tested it and now it is working as expected:
=> DE-460 - Campaign step

Doppler.HtmlEditorApi.Test/GetCampaignTest.cs, Doppler.HtmlEditorApi.Test/HtmlContentProcessingIntegrationTests.cs, Doppler.HtmlEditorApi.Test/Utils/AssertHelper.cs, Doppler.HtmlEditorApi/Controllers/CampaignsController.cs, Doppler.HtmlEditorApi/Doppler.HtmlEditorApi.csproj, Doppler.HtmlEditorApi/DopplerHtmlParser.cs, Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/ContentRow.cs, Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/FirstOrDefaultContentWithCampaignStatusDbQuery.cs, Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/InsertCampaignContentDbQuery.cs, Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/UpdateCampaignContentDbQuery.cs, Doppler.HtmlEditorApi/Storage.DapperProvider/Repository.cs, Doppler.HtmlEditorApi/Storage.DummyProvider/DummyRepository.cs, Doppler.HtmlEditorApi/Storage/ContentData.cs
It is an alternative to #51
> I am following almost the same Doppler behavior to split head and body parts of the HTML content.
> 
> Notice that the behavior to write and read the content is not symmetric. So. when you read the HTML you will lose information as it happens with Doppler.
> 
> At this moment, it does not affect us because the Drag-n-drop Unlayer Editor does not use the HTML content, and the Classic Unlayer HTML Editor ignores the head. It could only affect us if we want to edit imported content with the Classic Unlayer HTML Editor.
I like this implementation because it is less procedural than #51. In my opinion, it is part of the core of the domain logic of this API and probably we will never replace _HtmlAgilityPack_ with another thing. It is also simpler and allows us to …
=> DE-474 - Split body and head (alternative implementation)

Doppler.HtmlEditorApi.Test/HtmlContentProcessingIntegrationTests.cs, Doppler.HtmlEditorApi/Controllers/CampaignsController.cs, Doppler.HtmlEditorApi/DopplerFieldsProcessor.cs, Doppler.HtmlEditorApi/DopplerHtmlDocument.cs, Doppler.HtmlEditorApi/Field.cs, Doppler.HtmlEditorApi/FieldAliasesDef.cs
Hi team!
Thanks to the help of @mmosquera, @ms-darianbenito, @Cromeror, and @maurocardinali, I think that I found a nice set of abstractions to do this work and the following one (deal with links, restore field name tags on load, etc).
I have renamed the class `DopplerHtmlParser` by `DopplerHtmlDocument`. It is responsible for dealing with the low-level details preparing the HTML content.
And the new class `DopplerFieldsProcessor` is responsible for the translations between field names and filed ids. It does not know anything about HTML or tag delimiters (`[[[`, `|*|`, etc).
I am not using interfaces nor injecting them as dependencies, see a [related discussion in Slack](https://makingsense.slack.com/archives/C1KJY4K6V/p1646223318888339).
There is more work to do here:
- …
=> DE-472 - Convert field name tags to field id tags on saving content (step 1)

Doppler.HtmlEditorApi.Test/HtmlContentProcessingIntegrationTests.cs, Doppler.HtmlEditorApi/DopplerHtmlDocument.cs, Doppler.HtmlEditorApi/HtmlAgilityPack/HtmlAgilityPackUtils.cs
Hi team!
It is a continuation of #55.
I am replacing the field name tags making honor of HTML structure. I understand that the behavior could change, but I think that it is safer and more extensible.
I am accepting `%20` as space in field names. Doppler was already doing it, probably because some user has an issue with his HTML editor tool.
I am also accepting HTML Entities in the field names, for example in `[[[cumpleaños]]]`. Doppler was not doing it, but I think that it is a reasonable improvement in order to make it robust.
Could you review?
=> DE-500 - Traversing HTML to transform field tags

Doppler.HtmlEditorApi.Test/DopplerHtmlDocumentTest.cs, Doppler.HtmlEditorApi.Test/HtmlContentProcessingIntegrationTests.cs, Doppler.HtmlEditorApi/Controllers/CampaignsController.cs, Doppler.HtmlEditorApi/DopplerHtmlDocument.cs, Doppler.HtmlEditorApi/HtmlAgilityPack/HtmlAgilityPackUtils.cs, Doppler.HtmlEditorApi/Utils.cs
Hi team!
It reproduces old Doppler behavior sanitizing trackable link URLs.
The behavior is not exactly the same, because I tried to reproduce the original developer objectives but I tried to do it in a cleaner and more robust way.
Description of the new behavior: 
1. It searches the non-empty hrefs attributes in `a` and `area` elements, when it does not have a `socialshare` attribute. 
3. It only takes the href values that start with `http://`, `https://`, `ftp://`, or `www.` (ignoring leading whitespaces and `%20` occourences)
4. It removes leading and trailing occurrences of `%20` (arguable, but Doppler does it)
5. It removes all spaces
6. It converts to lowercase the schema and domain, but keep the case for the rest of the URL
7. When the URL starts with `www.` and scheme is not …
=> DE-476 - Trackable links sanitization

Doppler.HtmlEditorApi.Test/DopplerFieldsProcessorTest.cs, Doppler.HtmlEditorApi.Test/DopplerHtmlDocumentTest.cs, Doppler.HtmlEditorApi/Controllers/CampaignsController.cs, Doppler.HtmlEditorApi/DopplerFieldsProcessor.cs, Doppler.HtmlEditorApi/DopplerHtmlDocument.cs
Hi team!
I have already sanitized the links in #70, now I am reading them to then (in further PR) insert them in the database.
When it reads the links, it transforms back the internal field representation (`|*|{ID}*|*`) into the public representation  (`[[[name]]]`) using the canonical field name.
=> DE-476 - Link list

Doppler.HtmlEditorApi.Test/DopplerHtmlDocumentTest.cs, Doppler.HtmlEditorApi/Controllers/CampaignsController.cs, Doppler.HtmlEditorApi/DopplerHtmlDocument.cs
I was confused when I review the old Doppler code, when we obtain the trackable links, they should be in raw format (I mean, with the id in place of the name) as you can see in the image:
So, I am removing the wrong behavior in this PR.
=> fix: do not map field ids to field names on GetTrackableUrls()

Doppler.HtmlEditorApi.Test/SaveCampaignTest.cs, Doppler.HtmlEditorApi/Storage.DapperProvider/DapperCampaignContentRepository.cs, Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/DeleteAutomationConditionalsOfRemovedCampaignLinks.cs, Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/DeleteRemovedCampaignLinks.cs
Hi team!
This is the query to delete the links removed from the campaign content.
It was easier than insert because of a [Dapper feature](https://github.com/DapperLib/Dapper#list-support). It is not so predictable, so I have added a code comment with the explanation.
It is pending:
=> DE-530 - Delete removed links and related AutomationConditionals

Doppler.HtmlEditorApi.Test/Storage/Queries/DapperProvider/DapperCampaignContentRepositoryTest.cs, Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/PutCampaignTest.cs, Doppler.HtmlEditorApi/CampaignState.cs, Doppler.HtmlEditorApi/CampaignStatus.cs, Doppler.HtmlEditorApi/Controllers/CampaignsController.cs, Doppler.HtmlEditorApi/Storage.DapperProvider/DapperCampaignContentRepository.cs, Doppler.HtmlEditorApi/Storage.DapperProvider/Queries/FirstOrDefaultCampaignStatusDbQuery.cs, Doppler.HtmlEditorApi/Storage/ICampaignContentRepository.cs
Se agrega la verificación del estado de una campaña para permitir o denegar la edición del contenido de acuerdo a la homologación de los [estados manejados en Doppler](https://github.com/MakingSense/Doppler/blob/develop/Doppler.Transversal/Classes/CampaignStatusEnum.cs). Para la homologación se abstrajo la [lógica de Doppler](https://github.com/MakingSense/Doppler/blob/ed24e901c990b7fb2eaeaed557c62c1adfa80215/Doppler.Application.CampaignsModule/Services/Classes/CampaignContentService.cs#L2506-L2509).
⚠️ _**Importante,**_ el manejo de estados en esta api se construirá homologando los estados que maneja Doppler, esto significa que es necesario hacer un análisis de los estados antes de agregarlos acá teniendo en cuenta [CampaignShippingStatus.cs](https://github.com/MakingSense/Doppler/blob/de …
=> [DE-478] Denegar la edición de campañas con estados no permitidos

Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/PutCampaignTest.cs, Doppler.HtmlEditorApi/Controllers/CampaignsController.cs, Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerCampaignContentRepository.cs, Doppler.HtmlEditorApi/Repositories/ICampaignContentRepository.cs
Para evitar una consulta doble del estado de una campaña se ve oportuno separar el método `saveCampaignContent()` en dos métodos _(update, create)_ y que el controlador que es quien conoce la información del estado de una campaña se encargue de decidir que método usar.
=> WIP: [DE-478] refactorización del metodo saveCampaignContent

Doppler.HtmlEditorApi.Test/Domain/DopplerHtmlDocumentTest.cs, Doppler.HtmlEditorApi/Domain/DopplerHtmlDocument.cs
`_contentNode.SelectNodes()` was returning nodes that were not descendants of `_contentNode` but of `_headNode`. It is weird, but maybe it is expected in _HtmlAgilityPack_.
Anyway, to make it clear, I added a `_rootNode` that includes `_contentNode` and, if it exists, `_headNode`.
I have also done some improvements in the tests to confirm that the element case was not being taken into account in RemoveHarmfulTags.
=> fix: use rootNode in place of contentNode to remove harmfultags

Doppler.HtmlEditorApi.Test/Domain/DopplerHtmlDocumentTest.cs, Doppler.HtmlEditorApi/Controllers/CampaignsController.cs, Doppler.HtmlEditorApi/Domain/DopplerHtmlDocument.cs
Hi team, 
I think that I am concluding with the user story with this PR. Feel free to only pay attention to the last commit because the other commits are shared with #92.
It searches for all attributes with names starting with `on` and removes them from the document.
=> DE-477 - Remove event attributes

Doppler.HtmlEditorApi/ApiModels/Template.cs, Doppler.HtmlEditorApi/Controllers/CampaignsController.cs, Doppler.HtmlEditorApi/Domain/TemplateData.cs, Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerDbServiceCollectionExtensions.cs, Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerTemplateRepository.cs, Doppler.HtmlEditorApi/Repositories.DopplerDb/Queries/GetTemplateByIdWithStatusDbQuery.cs, Doppler.HtmlEditorApi/Repositories/ITemplateRepository.cs, demo.http
Como parte de la tarea [DE-574](https://makingsense.atlassian.net/browse/DE-574) se agrega el endpoint _/accounts/{username}/campaigns/{campaignId}/content/from-template/{templateId}_ para la creación del contenido de una campaña a partir de un template publico/privado.
_Restricciones de la funcionalidad:_
- No se pueden crear contenido con templates inactivos
- No se puede crear contenido con templates privados que no pertenezcan al usuario
Tarea: [[DE-605]](https://makingsense.atlassian.net/browse/DE-605)
[DE-605]: https://makingsense.atlassian.net/browse/DE-605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DE-605] crear campaña a partir de un unlayer template

Doppler.HtmlEditorApi.Test/Repositories.DopplerDb/DopplerCampaignContentRepositoryTest.cs, Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerCampaignContentRepository.cs, Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerDbServiceCollectionExtensions.cs, Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerFieldsRepository.cs, Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerTemplateRepository.cs
Para mantener la consistencia con la [arquitectura planteada](https://raw.githubusercontent.com/FromDoppler/doppler-html-editor-api/main/docs/project-architecture.svg) se renombro las clases con prefijo Dapper por Doppler según corresponde.
=> Renombrado los repositorios con prefijo Dapper

Doppler.HtmlEditorApi.Test/Repositories.DopplerDb/DopplerTemplateRepositoryTest.cs, Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/from-template/_/CreateCampaignContentFromTemplateTest.cs, Doppler.HtmlEditorApi/Domain/TemplateData.cs, Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerCampaignContentRepository.cs, Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerTemplateRepository.cs
Se heredaron las pruebas de _**SaveCampaign**_ y se prueba al obtener templates.
[[DE-605]](https://makingsense.atlassian.net/browse/DE-605)
[DE-605]: https://makingsense.atlassian.net/browse/DE-605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DE_605] Probar contenido de campaña creado a partir de un template

Doppler.HtmlEditorApi.Test/Repositories.DopplerDb/Queries/UpdateCampaignContentDbQueryTest.cs, Doppler.HtmlEditorApi.Test/Utils/IDbContextMockExtensions.cs, Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/GetCampaignTest.cs, Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/from-template/_/CreateCampaignContentFromTemplateTest.cs, Doppler.HtmlEditorApi/Controllers/CampaignsController.cs, Doppler.HtmlEditorApi/Domain/ContentData.cs, Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerCampaignContentRepository.cs, Doppler.HtmlEditorApi/Repositories.DopplerDb/Queries/FirstOrDefaultContentWithCampaignStatusDbQuery.cs, Doppler.HtmlEditorApi/Repositories.DopplerDb/Queries/InsertCampaignContentDbQuery.cs, Doppler.HtmlEditorApi/Repositories.DopplerDb/Queries/UpdateCampaignContentDbQuery.cs
Ahora se almacena el IdTemplate cuando se crea un contenido desde una plantilla
[[DE-683]](https://makingsense.atlassian.net/browse/DE-683)
[DE-683]: https://makingsense.atlassian.net/browse/DE-683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DE-683] almacenando idTemplate al guardar contenido de campaña

Doppler.HtmlEditorApi/DopplerCors/DopplerCorsMiddlewareExtensions.cs, Doppler.HtmlEditorApi/Startup.cs
Based on <https://httptoolkit.tech/blog/cache-your-cors/#cors-caching-for-cdns>
I know that this code is not so elegant, but at least it is small and it is all in a single place.
=> CORS cache instruction for CDNs

Doppler.HtmlEditorApi.Test/Repositories.DopplerDb/DopplerTemplateRepositoryTest.cs, Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/GetCampaignTest.cs, Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/from-template/_/CreateCampaignContentFromTemplateTest.cs, Doppler.HtmlEditorApi/ApiModels/CampaignContent.cs, Doppler.HtmlEditorApi/ApiModels/Content.cs, Doppler.HtmlEditorApi/Controllers/CampaignsController.cs, Doppler.HtmlEditorApi/Domain/CampaignContentData.cs, Doppler.HtmlEditorApi/Domain/CampaignModel.cs, Doppler.HtmlEditorApi/Domain/TemplateContentData.cs, Doppler.HtmlEditorApi/Domain/TemplateModel.cs, Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerCampaignContentRepository.cs, Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerTemplateRepository.cs, Doppler.HtmlEditorApi/Repositories/ICampaignContentRepository.cs, Doppler.HtmlEditorApi/Repositories/ITemplateRepository.cs
Hi team!
I think that we needed this code refactoring.
Now, content and campaign objects are two different things, it fixes our log time issue with preview images and also some new issues with the name. Now, `CampaignId`, `Name`, `PreviewImage` and `Content` are part of the `CampaignModel`.
I did the same with Templates, but I cannot reuse the same `Content` class because template content has a different structure merging `HtmlHead` and `HtmlContent` in the single field `HtmlComplete`.
To expose the data, the model is still being flattened in `CampaignContent`, we could consider this object like a _campaign's content + some campaign information_. For that reason, I have also removed `previewImage` field from `Content` class.
=> Split campaign and content

Doppler.HtmlEditorApi/Domain/DopplerHtmlDocument.cs, Doppler.HtmlEditorApi/Logging/SerilogSetup.cs
Fix these errors:
```
Doppler.HtmlEditorApi/Logging/SerilogSetup.cs(18,13): error CA1305: The behavior of '{0}' could vary based on the current user's locale settings. Provide a value for the 'IFormatProvider' argument. [Doppler.HtmlEditorApi/Doppler.HtmlEditorApi.csproj]
Doppler.HtmlEditorApi/Domain/DopplerHtmlDocument.cs(64,26): error CA1305: The behavior of '{0}' could vary based on the current user's locale settings. Provide a value for the 'IFormatProvider' argument. [Doppler.HtmlEditorApi/Doppler.HtmlEditorApi.csproj]
Doppler.HtmlEditorApi/Logging/SerilogSetup.cs(28,17): error CA1305: The behavior of '{0}' could vary based on the current user's locale settings. Provide a value for the 'IFormatProvider' argument. [Doppler.HtmlEditorApi/Doppler.HtmlEditorApi.csproj] …
```
=> chore(CodeQuality): add explicit formatProvider

Doppler.HtmlEditorApi.Test/Repositories.DopplerDb/DopplerCampaignContentRepositoryTest.cs, Doppler.HtmlEditorApi.Test/Repositories.DopplerDb/DopplerTemplateRepositoryTest.cs
Although xUnit supports `async void` (see https://github.com/xunit/xunit/issues/1405), I think that we should try to avoid this construction.
What do you think?
=> Replace `async void` for `async Task`

Doppler.HtmlEditorApi.Test/Repositories.DopplerDb/DopplerTemplateRepositoryTest.cs, Doppler.HtmlEditorApi.Test/http/accounts/_/templates/_/GetTemplateTest.cs, Doppler.HtmlEditorApi.Test/http/accounts/_/templates/_/PutTemplateTest.cs, Doppler.HtmlEditorApi.Test/http/accounts/_/templates/_/from-template/_/PostTemplateFromTemplateTest.cs, Doppler.HtmlEditorApi/ApiModels/ResourceCreated.cs, Doppler.HtmlEditorApi/Controllers/TemplatesController.cs, Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerTemplateRepository.cs, Doppler.HtmlEditorApi/Repositories.DopplerDb/Queries/CreatePrivateTemplateDbQuery.cs, Doppler.HtmlEditorApi/Repositories/ITemplateRepository.cs
Hi team!
These changes allow us to create templates based on another template.
Related to https://github.com/MakingSense/Doppler/pull/9883
There are some refactorings in this PR because [I learn about TypedResults](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#typed-results-for-minimal-apis) and I really liked them. In following steps I will be migrating all the API from `IActionResult` to typed `IResult`.
Could you review?
=> DE-901 - Support template creation

Doppler.HtmlEditorApi.Test/http/accounts/_/templates/_/from-template/_/PostTemplateFromTemplateTest.cs, Doppler.HtmlEditorApi/Controllers/TemplatesController.cs
Add _**queryParam**_ to change the name in the creation of a new template from another template, the param is optional.
_**ROUTE**_ `/accounts/{accountName}/templates/from-template/{baseTemplateId}?templateName=NewNameTemplate`
=> [DE-865] Duplicate template using a custom name

Doppler.HtmlEditorApi.Test/Repositories.DopplerDb/Queries/UpdateCampaignStatusDbQueryTest.cs, Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/PutCampaignTest.cs, Doppler.HtmlEditorApi.Test/http/accounts/_/campaings/_/content/from-template/_/CreateCampaignContentFromTemplateTest.cs, Doppler.HtmlEditorApi/Controllers/CampaignsController.cs, Doppler.HtmlEditorApi/Repositories.DopplerDb/DopplerCampaignContentRepository.cs, Doppler.HtmlEditorApi/Repositories.DopplerDb/Queries/UpdateCampaignStatusDbQuery.cs, Doppler.HtmlEditorApi/Repositories/ICampaignContentRepository.cs
When Automation campaigns are in the _step 1_, his _ContentType is 0_ (undefined), while in the regular campaigns, it is 1 (text) or 2 (HTML).
These changes allow us to deal with this scenario.
=> DBG-209 - Set ContentType in Automation Unlayer campaigns

Doppler.HtmlEditorApi.Test/Domain/DopplerHtmlDocumentTest.cs, Doppler.HtmlEditorApi/Controllers/CampaignsController.cs, Doppler.HtmlEditorApi/Domain/DopplerHtmlDocument.cs, cspell-project-words.txt
Add process to adapt dynamic content to automation HTML syntactic rules
- remove redundant cart items (html nodes)
- replace img src by [[[DC:IMAGE]]]
=> DOP-1397 - add sanitize content for dynamic component

Doppler.HtmlEditorApi/Domain/DopplerHtmlDocument.cs
Si el nodo DynamicContent tiene presente el atributo "data-dc-type" no debería realizar el siguiente seteo:
```imgNode.SetAttributeValue("src", "[[[DC:IMAGE]]]");```
=> fix: do not set attribute if data dc type is present

Doppler.HtmlEditorApi/Domain/DopplerHtmlDocument.cs
Se recorre un array de posibles substrings que contiene la url de la imagen para decidir si setear o no el atributo ```[[[DC:IMAGE]]]```
=> Big Box problema con imagenes
